### ISSUE TITLE
Operations Manager Eventlog Spam

### ISSUE THREAD

**Issue by ZHumphries** [PureStorage-Connect/SCOM-Management-Pack#1]
Version: 1.1.99.0

The pure management pack is spamming the Operations Manager log with performance metrics. Every single metric for every array is being logged as an informational message. In our case this generating around 11,000 events per hour on the management servers and making the log very difficult to use.

Example Logs.
03/12/2020 08:34:57           2104 Information      HostPerformanceRule.ps1 [1.1.99.0] : Saving metric : @{writes_per_sec=0; name=host1; usec_per_write_op=0; output_per_sec=5631; san_usec_per_read_op=1; reads_per_sec=7; input_per_sec=0; time=12/03/2020 08:34:57; san_usec_per_write_op=0; usec_per_read_op=237}
03/12/2020 08:34:57           2104 Information      HostPerformanceRule.ps1 [1.1.99.0] : Saving metric : @{writes_per_sec=0; name=host2; usec_per_write_op=0; output_per_sec=8191; san_usec_per_read_op=1; reads_per_sec=2; input_per_sec=0; time=12/03/2020 08:34:57; san_usec_per_write_op=0; usec_per_read_op=457}
03/12/2020 08:34:57           2104 Information      HostPerformanceRule.ps1 [1.1.99.0] : Saving metric : @{writes_per_sec=0; name=host3; usec_per_write_op=0; output_per_sec=4095; san_usec_per_read_op=2; reads_per_sec=1; input_per_sec=0; time=12/03/2020 08:34:57; san_usec_per_write_op=0; usec_per_read_op=130}
03/12/2020 08:34:57           2104 Information      HostPerformanceRule.ps1 [1.1.99.0] : Saving metric : @{writes_per_sec=0; name=host4; usec_per_write_op=0; output_per_sec=4095; san_usec_per_read_op=1; reads_per_sec=1; input_per_sec=0; time=12/03/2020 08:34:57; san_usec_per_write_op=0; usec_per_read_op=162}

**Comment by mikenelson-io** [comment]
Have you altered the thresholds from the defaults to suit your environment? Also, the latest 1.2.7.0 release addresses some of the alert issues.

**Comment by ZHumphries** [comment]
Yes I have increased the collection frequency. While this will increase the amount of messages generated, I do not believe this kind of information should be logged to the Operations Manager log. 

Maybe it would be useful to have an override to enable debug or some such so as not to fill the log with performance metrics. Or a single log entry with a summary of everything collected in that run.

**Comment by mikenelson-io** [comment]
RFE created.
