### ISSUE TITLE
Port Alerts missing basic information

### ISSUE THREAD

**Issue by ZHumphries** [PureStorage-Connect/SCOM-Management-Pack#2]
There alert for ports on the flash array is are missing names/descriptions, providing no context to the engineer in scom.

![image](https://user-images.githubusercontent.com/24667546/100986122-b2475680-3544-11eb-8e13-2d7633b01e34.png)

**Comment by mikenelson-io** [comment]
I believe this is addressed in 1.2.7.0, but I'll check. If not, it will be in an upcoming release.

**Comment by mikenelson-io** [comment]
Resolved in 1.2.7.0.
