### ISSUE TITLE
Latency alerts include no unit of measurement

### ISSUE THREAD

**Issue by ZHumphries** [PureStorage-Connect/SCOM-Management-Pack#3]
Alert Description
Host Read Latency (29438) exceeds the configured monitoring threshold.

Please include the unit of measurement in the alert as I do not think this is in 'ms' as stated in the documentation.

**Comment by mikenelson-io** [comment]
I believe this is corrected in 1.2.7.0.

**Comment by mikenelson-io** [comment]
It was not corrected in the latest release. I will create an RFE to add this in the parameter description.
Latency metrics are in microseconds (usec).

**Comment by mikenelson-io** [comment]
Will be corrected in next release.
