### ISSUE TITLE
Duplicate REST API Alerts

### ISSUE THREAD

**Issue by ZHumphries** [PureStorage-Connect/SCOM-Management-Pack#4]
The alerts generated in SCOM for alerts from the pure array should be a monitor not a rule. The current implementation generates a new duplicate alert every time the rules runs. At the very least it should increment the alert count and not generate a new alert.

![image](https://user-images.githubusercontent.com/24667546/101276052-2894c480-37a2-11eb-98c5-823e0798bf78.png)

**Comment by mikenelson-io** [comment]
Submitted to development.
