### ISSUE TITLE
Request: Formatting of numbers in alerts

### ISSUE THREAD

**Issue by ZHumphries** [PureStorage-Connect/SCOM-Management-Pack#5]
Please add some formatting to numbers that are shown in the alerts, either by adding a separator (126,432,761) or by formatting the number with a unit (126K) as the number below is hard to read at a glance.

Array read operations per second (126432761) exceeded the  configured monitoring threshold.

**Comment by mikenelson-io** [comment]
Request sent to Development.

**Comment by mikenelson-io** [comment]
Added to next release.
